#to postgresql
db.url      = jdbc:postgresql://localhost:5433/appdb
db.user     = postgres
db.password = 123456
db.driver   = org.postgresql.Driver

#to mysql
#db.url      = jdbc:mysql://localhost:3306/appdb
#db.user     = root
#db.password = secret
#db.driver   = com.mysql.cj.jdbc.Driver